version: '3.8'
services:
  telegram-bot-terminator:
    container_name: telegram-bot-terminator
    image: the-matrix/python
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_WEBHOOK_URL: ${TELEGRAM_WEBHOOK_URL}
      TELEGRAM_BOT_LISTEN_PORT: ${TELEGRAM_BOT_LISTEN_PORT}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
    ports:
      - "8080:80/tcp"
    volumes:
      - type: bind
        source: ./script
        target: /script
    working_dir: /script
    command: [ "python3", "-u", "main.py" ]
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: telegram-bot-terminator-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1qaz2wsx3edc
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    ports:
      - "27017:27017/tcp"
    restart: unless-stopped
volumes:
  mongodb: