version: '3.8'
services:
  telegram-captcha-bot:
    container_name: telegram-bot-terminator
    image: the-matrix/python
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_WEBHOOK_URL: ${TELEGRAM_WEBHOOK_URL}
      TELEGRAM_BOT_LISTEN_PORT: ${TELEGRAM_BOT_LISTEN_PORT}
    ports:
      - "8080:80/tcp"
    volumes:
      - type: bind
        source: ./script
        target: /script
    working_dir: /script
    command: [ "python3", "-u", "main.py" ]
    restart: unless-stopped
  telegram-captcha-bot-database:
    image: mysql
    container_name: telegram-captcha-bot-database
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --default-authentication-plugin=mysql_native_password --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-buffer-pool-size=1G --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx3edc
      MYSQL_DATABASE: telegram-captcha-bot
      MYSQL_USER: telegram-captcha-bot
      MYSQL_PASSWORD: 1qaz2wsx
    ports:
      - "3306:3306/tcp"
volumes:
  database:
